eye:
  input_directory: "./"
  input_extensions: "*.html,*.js"
  #  input_exact_files: "index.html"

  exclude_directory: ".git"
  exclude_files: ".gitignore"

  output_name: "./assets/css/watched_eye.css"